CREATE TABLE Signup(
user_id INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
Full_Name VARCHAR(50) NOT NULL,
Email VARCHAR(100) UNIQUE NOT NULL,
Username VARCHAR(100) UNIQUE NOT NULL,
Password VARCHAR(100) NOT NULL);